import type { Metadata } from "next";
import "./globals.css";
import { Inter as FontSans } from 'next/font/google'
import { cn } from "@/lib/utils";
import envConfig from "../config";
import { Toaster } from "@/components/ui/toaster";
import Link from "next/link";
import Script from "next/script";

const fontSans = FontSans({
  subsets: ['latin'],
  variable: '--font-sans'
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  console.log(envConfig.NEXT_PUBLIC_API_ENDPOINT);
  
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <meta charSet="UTF-8" />
        <meta name="description" content="Anime Template" />
        <meta name="keywords" content="Anime, unica, creative, html" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        {/* <meta http-equiv="X-UA-Compatible" content="ie=edge" /> */}
        <title>Anime | Template</title>
        <link href="https://fonts.googleapis.com/css2?family=Oswald:wght@300;400;500;600;700&display=swap" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css2?family=Mulish:wght@300;400;500;600;700;800;900&display=swap" rel="stylesheet" />
        <link rel="stylesheet" href="css/bootstrap.min.css" type="text/css" />
        <link rel="stylesheet" href="css/font-awesome.min.css" type="text/css" />
        <link rel="stylesheet" href="css/elegant-icons.css" type="text/css" />
        <link rel="stylesheet" href="css/plyr.css" type="text/css" />
        <link rel="stylesheet" href="css/nice-select.css" type="text/css" />
        <link rel="stylesheet" href="css/owl.carousel.min.css" type="text/css" />
        <link rel="stylesheet" href="css/slicknav.min.css" type="text/css" />
        <link rel="stylesheet" href="css/style.css" type="text/css" />
      </head>
      <body
        className={cn(
          'min-h-screen bg-background font-sans antialiased',
          fontSans.variable
        )}
      >
        <header className="header">
        <div className="container">
            <div className="row">
                <div className="col-lg-2">
                    <div className="header__logo">
                        <a href="./index.html">
                            <img src="img/logo.png" alt="" />
                        </a>
                    </div>
                </div>
                <div className="col-lg-8">
                    <div className="header__nav">
                        <nav className="header__menu mobile-menu">
                            <ul>
                                <li className="active"><a href="./index.html">Homepage</a></li>
                                <li><a href="./categories.html">Categories <span className="arrow_carrot-down"></span></a>
                                    <ul className="dropdown">
                                        <li><a href="./categories.html">Categories</a></li>
                                        <li><a href="./anime-details.html">Anime Details</a></li>
                                        <li><a href="./anime-watching.html">Anime Watching</a></li>
                                        <li><a href="./blog-details.html">Blog Details</a></li>
                                        <li><a href="./signup.html">Sign Up</a></li>
                                        <li><a href="./login.html">Login</a></li>
                                    </ul>
                                </li>
                                <li><a href="./blog.html">Our Blog</a></li>
                                <li><a href="#">Contacts</a></li>
                            </ul>
                        </nav>
                    </div>
                </div>
                <div className="col-lg-2">
                    <div className="header__right">
                        <a href="#" className="search-switch"><span className="icon_search"></span></a>
                        <a href="./login.html"><span className="icon_profile"></span></a>
                    </div>
                </div>
            </div>
            <div id="mobile-menu-wrap"></div>
        </div>
    </header>
        <Toaster />
        {children}
        <footer className="footer">
                <div className="page-up">
                    <Link href="#" id="scrollToTopButton"><span className="arrow_carrot-up"></span></Link>
                </div>
                <div className="container">
                    <div className="row">
                        <div className="col-lg-3">
                            <div className="footer__logo">
                                <Link href="./"><img src="img/logo.png" alt="" /></Link>
                            </div>
                        </div>
                        <div className="col-lg-6">
                            <div className="footer__nav">
                                <ul>
                                    <li className="active"><Link href="./">Homepage</Link></li>
                                    <li><Link href="./categories.html">Categories</Link></li>
                                    <li><Link href="./blog.html">Our Blog</Link></li>
                                    <li><Link href="#">Contacts</Link></li>
                                </ul>
                            </div>
                        </div>
                        <div className="col-lg-3">
                            <p>
                              Copyright &copy; All rights reserved | This template is made with <i className="fa fa-heart" aria-hidden="true"></i> by <Link href="https://colorlib.com" target="_blank">Colorlib</Link>
                            </p>

                          </div>
                      </div>
                  </div>
            </footer>

            <div className="search-model">
              <div className="h-100 d-flex align-items-center justify-content-center">
                <div className="search-close-switch"><i className="icon_close"></i></div>
                <form className="search-model-form">
                    <input type="text" id="search-input" placeholder="Search here....." />
                </form>
              </div>
            </div>
        <Script src="js/jquery-3.3.1.min.js" />
        <Script src="js/bootstrap.min.js" />
        <Script src="js/player.js" />
        <Script src="js/jquery.nice-select.min.js" />
        <Script src="js/mixitup.min.js" />
        <Script src="js/jquery.slicknav.js" />
        <Script src="js/owl.carousel.min.js" />
        <Script src="js/main.js" />
      </body>
    </html>
  );
}
